-- ==========================================================================
-- Migration: eine Kategorie gehört einem Konto
-- ==========================================================================
--
-- ERST DURCHLESEN, DANN VON HAND AUSFÜHREN (phpMyAdmin oder der mysql-Client).
-- Nichts in der Anwendung führt diese Datei aus, und Copilot führt eine
-- strukturelle Änderung nie von selbst aus.
--
-- Auf der Kommandozeile:
--   mysql -u <Benutzer> -p learning_app < database/add_category_owner.sql
--
-- Warum
--   Bis jetzt gehörte eine Kategorie niemandem: `categories` hatte keine Spalte,
--   die sagte, wessen sie ist, jeder Besucher sah also dieselben Lernbereiche.
--   Der nächste Schritt ist ein zweites Konto, und von da an darf eine Person
--   immer nur ihre eigenen Bereiche, Unterkategorien und Karten sehen.
--
--   Diese Datei fügt die Spalte hinzu und sonst nichts. Sie FÜLLT sie nicht und
--   fasst keine einzige vorhandene Zeile an: nach dieser Datei ist die Spalte
--   überall NULL, die Anwendung ignoriert sie vollständig und arbeitet genau wie
--   heute weiter. Das Füllen ist eine eigene Datei
--   (database/assign_category_owner.sql), damit der Wert geprüft werden kann,
--   bevor er geschrieben wird.
--
-- Die Spalte
--
--   owner_user_id  Das Konto, dem eine Kategorie gehört. Derselbe Typ wie
--                  `users.id` (`INT UNSIGNED`) und NULL-fähig, diese Datei kann
--                  also laufen, bevor jemand zugeordnet wurde.
--
--                  Sie gehört an `categories` und NICHT an `cards`: eine Karte
--                  liegt immer in genau einer Kategorie, der Besitzer der
--                  Kategorie ist also schon der Besitzer der Karte. Eine zweite
--                  Spalte an `cards` wäre eine zweite Wahrheit, die von der
--                  ersten wegdriften kann.
--
-- Warum der Fremdschlüssel RESTRICT ist und nicht CASCADE
--   CASCADE sieht wie die freundliche Wahl aus ("Konto löschen, seine Kategorien
--   gehen mit"), aber in diesem Schema kann es nie wirklich greifen: `cards`
--   zeigt mit ON DELETE RESTRICT auf `categories`, und `categories.parent_id`
--   zeigt mit RESTRICT auf sich selbst. MySQL würde versuchen, die
--   Kategoriezeilen zu löschen, während ihre Karten und Unterkategorien noch da
--   sind, und mit Fehler 1451 abbrechen (Cannot delete or update a parent row).
--   Eine Regel, die von einer anderen Regel blockiert wird, tut nur so, als wäre
--   sie ein Sicherheitsnetz.
--
--   Mit RESTRICT ist das Verhalten ehrlich und sichtbar: das Löschen eines
--   Kontos mit Kategorien scheitert laut, und die Anwendung entfernt den Baum
--   selbst, in der Reihenfolge, die die Fremdschlüssel verlangen - was sie heute
--   schon in `delete_category_tree()` tut.
--
-- Was sie tut
--   Ein ALTER TABLE: fügt die Spalte, ihren Index und den Fremdschlüssel hinzu.
--
-- Was sie NICHT tut
--   * kein DROP, kein RENAME, kein TRUNCATE, kein DELETE, kein UPDATE - kein
--     vorhandener Wert wird gelesen oder geschrieben
--   * keine andere Tabelle wird angefasst: `users`, `cards`,
--     `user_card_progress`, `card_exercises` und `study_sessions` behalten ihre
--     Spalten und ihre Zeilen
--   * die Spalte wird hier NICHT auf NOT NULL gesetzt. Das ist eine eigene,
--     spätere Datei, sobald jede Zeile einen Besitzer trägt und die Anwendung
--     ihn immer setzt.
--
-- Sicherheit
--   Die Spalte darf NULL sein, und genau das macht diesen Schritt harmlos: die
--   Anwendung kennt die Spalte noch nicht, sie läuft also unverändert.
--
--   Dieser Server ist MySQL 8.4, und das unterstützt "ADD COLUMN IF NOT EXISTS"
--   NICHT (das ist MariaDB-Syntax; auf MySQL ist es ein Syntaxfehler). Ein
--   zweiter Lauf dieser Datei hält deshalb mit
--
--     ERROR 1060 (42S21): Duplicate column name 'owner_user_id'
--
--   an und ändert nichts. Dieser Fehler ist die erwartete Antwort auf den
--   zweiten Lauf und kein Problem - er heißt nur, dass der Schritt schon getan
--   ist.
--
-- Vor dem Lauf prüfen
--   SELECT COLUMN_NAME FROM information_schema.COLUMNS
--    WHERE TABLE_SCHEMA = 'learning_app' AND TABLE_NAME = 'categories'
--      AND COLUMN_NAME = 'owner_user_id';
--   Erwartet davor: keine Zeile.   Erwartet danach: eine Zeile.
--
-- Nach dem Lauf prüfen
--   SHOW CREATE TABLE categories;
--   Erwartet: die Spalte `owner_user_id` int unsigned DEFAULT NULL, der
--   Schlüssel `idx_categories_owner` und die Bedingung `fk_categories_owner` mit
--   ON DELETE RESTRICT.
--
-- Zurücknehmen (nur falls du den alten Zustand je zurückhaben willst)
--   ALTER TABLE `categories`
--       DROP FOREIGN KEY `fk_categories_owner`,
--       DROP KEY `idx_categories_owner`,
--       DROP COLUMN `owner_user_id`;
-- ==========================================================================

ALTER TABLE `categories`
    ADD COLUMN `owner_user_id` INT UNSIGNED NULL
        COMMENT 'The account this category belongs to; NULL only until every row has been assigned'
        AFTER `parent_id`,
    ADD KEY `idx_categories_owner` (`owner_user_id`),
    ADD CONSTRAINT `fk_categories_owner`
        FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
