-- ==========================================================================
-- Erzeugte Übungen: die Zahlen, aus denen eine Aufgabe gebaut wird
-- ==========================================================================
--
-- ERST DURCHLESEN, DANN VON HAND AUSFÜHREN (phpMyAdmin oder der mysql-Client).
-- Nichts in der Anwendung führt diese Datei aus, und Copilot führt eine
-- strukturelle Änderung nie von selbst aus.
--
-- Auf der Kommandozeile:
--   mysql -u <Benutzer> -p learning_app < database/add_exercise_params.sql
--
-- Warum eine Spalte mehr
--   Eine Übungskarte entsteht, wenn sie gezeigt wird, die Karte muss also sagen,
--   WELCHE Art von Aufgabe sie ist und WELCHE Zahlen diese Aufgabe benutzen darf.
--   Die Aufgabenart ist schon gespeichert (card_exercises.exercise_type). Was noch
--   fehlt, ist die zweite Hälfte: die Zahlen, und bei manchen Aufgabenarten eine
--   Auswahl zwischen Varianten.
--
--   Genau das hält exercise_params, als JSON. Für ein Malnehmen ist es
--
--     {"min": 2, "max": 20}
--
--   für eine Prozentaufgabe
--
--     {"min": 10, "max": 1000, "ask": "rate"}
--
--   und für die Energie-Prozentsätze die Liste der Zusammenhänge, die gezeigt
--   werden dürfen
--
--     {"variants": ["mix", "pv_ratio", "storage_level"]}
--
--   Welche Schlüssel erlaubt sind, was sie enthalten dürfen und was sie bedeuten,
--   steht an EINER Stelle: exercise_catalog() in src/services/exercise_service.php.
--   Ein Schlüssel, der nicht in dieser Liste steht, oder ein Wert außerhalb seiner
--   Grenzen wird beim Speichern der Karte abgelehnt und beim Lesen übergangen (die
--   Aufgabe fällt dann auf die Vorgaben ihrer Art zurück). Ein Schlüssel kann also
--   nie eine Formel in die Anwendung schmuggeln: hier wird nichts je als Text
--   ausgerechnet, nur nachgesehen.
--
--   NULL heißt "nimm die Vorgaben dieser Aufgabenart", und das bekommt jede Zeile,
--   die es heute gibt.
--
-- Was sie tut
--   Fügt genau eine NULL-fähige Spalte zu `card_exercises` hinzu. Sonst nichts.
--
-- Was sie NICHT tut
--   * sie fasst `cards` nicht an: keine neue Spalte, keine geänderte Spalte,
--     keine entfernte Spalte. Eine Karte ohne Zeile in `card_exercises` bleibt
--     eine feste Karte, und jede Karte, die es gibt, ist genau das
--   * kein DROP, kein RENAME, kein TRUNCATE, kein DELETE, kein UPDATE
--     vorhandener Werte
--   * keine andere Tabelle wird angefasst: `users`, `categories`, `cards` und
--     `user_card_progress` bleiben genau, wie sie sind
--   * sie nennt kein `card_kind`: ob eine Karte erzeugt wird, beantwortet schon
--     die Frage, ob sie eine Zeile in `card_exercises` hat. Eine zweite Spalte,
--     die dasselbe sagt, könnte der ersten widersprechen, also gibt es keine
--
-- Sicherheit
--   Ein zweiter Lauf dieser Datei ist in der Wirkung harmlos, antwortet aber mit
--   "#1060 - Duplicate column name". Das ist kein Problem: es heißt, dass die
--   Spalte schon da ist und nichts mehr zu tun bleibt.
--
--   Die Anweisung ist absichtlich schlicht geschrieben, ohne "IF NOT EXISTS":
--   diese Schreibweise gibt es in MariaDB, aber NICHT in MySQL, und dieser Server
--   ist MySQL 8.4. Die erste Fassung dieser Datei benutzte sie, und MySQL hat sie
--   mit "#1064" abgelehnt. Ein schlichtes "ADD COLUMN" verstehen beide.
--
--   Die Spalte darf NULL sein und die Tabelle war beim Anlegen leer, es kann also
--   in keiner Richtung ein vorhandener Wert betroffen sein.
--
-- Zurücknehmen (nur falls du den alten Zustand je zurückhaben willst)
--   ALTER TABLE `card_exercises` DROP COLUMN `exercise_params`;
--
-- Zwei Spalten aus dem ersten Schritt bleiben unangetastet
--   `range_min` und `range_max` kamen mit der ersten Fassung dieser Tabelle und
--   sind leer. Die Zahlen stehen jetzt in `exercise_params`, die beiden werden
--   also nicht mehr geschrieben. Sie bleiben stehen, weil das Entfernen einer
--   Spalte nichts ist, was diese Datei entscheiden sollte; wenn du sie weghaben
--   willst, ist das die Zeile dafür:
--
--     ALTER TABLE `card_exercises` DROP COLUMN `range_min`, DROP COLUMN `range_max`;
-- ==========================================================================

ALTER TABLE `card_exercises`
    ADD COLUMN `exercise_params` JSON NULL
        COMMENT 'The numbers this task is built from, as JSON; which keys are allowed is written down in exercise_catalog()'
        AFTER `exercise_type`;
