-- Daten: die vorhandenen Kategorien ihrem Konto übergeben
-- ==========================================================================
--
-- ERST DURCHLESEN, DANN VON HAND AUSFÜHREN (phpMyAdmin oder der mysql-Client).
-- Nichts in der Anwendung führt diese Datei aus, und Copilot ändert deine Daten
-- nie von selbst.
--
-- Auf der Kommandozeile:
--   mysql -u <Benutzer> -p learning_app < database/assign_category_owner.sql
--
-- Erst NACH database/add_category_owner.sql ausführen. Ohne diese Spalte gibt es
-- hier nichts zu füllen.
--
-- Warum
--   `owner_user_id` gibt es seit der Migration oben, und jede Zeile ist NULL.
--   Solange das nicht gefüllt ist, kann die Anwendung weiterhin nicht sagen,
--   wessen diese Kategorien sind - diese Datei schreibt den Besitzer also einmal
--   für jede Zeile, die keinen hat.
--
-- Das Konto
--
--   id    6
--   name  selina.schneider
--   email selina.schneider@gmail.com
--   role  learner
--
--   Diese Id wurde aus der Tabelle `users` gelesen und von der Kontoinhaberin
--   bestätigt, bevor diese Datei geschrieben wurde. Es ist das einzige Konto in
--   der Tabelle. Die Id steht absichtlich wörtlich da und wird nicht über die
--   E-Mail-Adresse gesucht: eine einmalige Nachfüllung soll sagen, welche Id sie
--   schreibt, damit die Anweisung geprüft werden kann, ohne eine zweite Abfrage
--   im Kopf zu haben.
--
--   Prüf es vor dem Lauf selbst (erwartet: genau eine Zeile, id 6):
--
--     SELECT id, name, email, role FROM users ORDER BY id;
--
-- Was sie tut
--   Ein UPDATE. Sie setzt `owner_user_id = 6` auf jeder Kategoriezeile, die noch
--   keinen Besitzer hat - die 4 Lernbereiche und ihre 41 Unterkategorien, 45
--   Zeilen insgesamt (gezählt am 2026-09-26, nachdem die englischen
--   Unterkategorien entfernt wurden). Seither sind Kategorien dazugekommen; die
--   Zahl beschreibt also den damaligen Stand.
--
--   Sonst ändert sich nichts: kein Name, keine Farbe, keine Zeichnung, kein
--   Elternteil, keine Karte. Die Zeilen behalten ihre Ids, jede Karte bleibt also
--   in der Kategorie, in der sie war.
--
-- Was sie NICHT tut
--   * kein INSERT, kein DELETE, kein DROP, kein ALTER - die Struktur wird nicht
--     angefasst
--   * keine andere Tabelle wird angefasst: `users`, `cards`,
--     `user_card_progress`, `card_exercises` und `study_sessions` behalten ihre
--     Zeilen genau, wie sie sind
--   * sie setzt die Spalte nicht auf NOT NULL. Das ist eine eigene, spätere
--     Datei, sobald die Anwendung den Besitzer immer selbst setzt.
--   * sie filtert noch nichts. Die Anwendung liest die Spalte erst mit der
--     Codeänderung, die darauf folgt, diese Datei allein ändert also kein
--     Verhalten, das du sehen kannst.
--
-- Sicherheit
--   Die WHERE-Bedingung fasst nur Zeilen an, die noch leer sind. Ein zweiter Lauf
--   dieser Datei meldet deshalb
--
--     0 rows affected
--
--   und ändert nichts - und genau das willst du auch, wenn eine Kategorie später
--   einmal an ein anderes Konto geht: diese Datei nimmt sie nicht zurück.
--
-- Nach dem Lauf prüfen (erwartet: 45 und 45)
--   SELECT COUNT(*) AS gesamt,
--          COUNT(owner_user_id) AS mit_besitzer
--     FROM categories;
--
--   Erwartet: 45 Zeilen tragen Besitzer 6, 0 Zeilen sind NULL.
--
--   SELECT owner_user_id, COUNT(*) FROM categories GROUP BY owner_user_id;
--
--   Erwartet: eine einzige Zeile, Besitzer 6, Anzahl 45.
--
-- Zurücknehmen (nur falls du den alten Zustand je zurückhaben willst)
--   UPDATE `categories` SET `owner_user_id` = NULL WHERE `owner_user_id` = 6;
-- ==========================================================================

UPDATE `categories`
   SET `owner_user_id` = 6
 WHERE `owner_user_id` IS NULL;
