-- ===========================================================================
--  Bilingual flashcards: one German and one English question and answer
-- ===========================================================================
--
--  STATE OF THE TABLE (checked on 2026-09-21 against `learning_app`)
--
--      SHOW COLUMNS FROM cards:
--
--          id               int unsigned  NOT NULL
--          category_id      int unsigned  NOT NULL
--          front            text          NOT NULL   <- German, kept in step
--          back             text          NOT NULL   <- German, kept in step
--          front_de         text          NULL       <- the German question
--          back_de          text          NULL       <- the German answer
--          front_en         text          NULL       <- the English question
--          back_en          text          NULL       <- the English answer
--          is_bidirectional tinyint(1)    NOT NULL
--
--      Rows with text: front 161, back 161, front_de 161, back_de 161,
--                      front_en 0, back_en 0
--
--  IN OTHER WORDS: THE MIGRATION IS ALREADY DONE.
--  All four language columns exist and the 161 cards carry their German text in
--  front_de and back_de. Nothing in this file has to be run - it documents the
--  shape the application expects, so the state can be checked again later.
--
--  WHY front AND back STILL EXIST
--  They are NOT NULL and every card has always carried its German text there.
--  They are not dropped and not renamed, because that would change data nobody
--  asked to change. The application writes the German text into front_de/back_de
--  AND into front/back, so the two stay identical and a reader of the old shape
--  never sees an empty card.
--
--  WHAT THE APPLICATION DOES WITH IT
--      * German  = front_de / back_de     English = front_en / back_en
--      * the app asks the table which columns it has, so a database without the
--        *_de/*_en columns simply stays single-language (German in front/back)
--      * a card may be German only, English only or both; at least one complete
--        language (question AND answer) is required
--      * a card that has only one language is shown in that language, with a
--        quiet "only German" / "only English" next to it
--      * one learning progress per card, for both languages, unchanged
--        (user_card_progress keeps its shape)
--
-- ===========================================================================
--  THE SAME CHANGE FOR A FRESH DATABASE (do NOT run it where the columns exist)
-- ===========================================================================
--
--  On an empty database, or on a copy that predates the language columns, this
--  is the migration - it only ADDS columns and copies the German text into the
--  new German columns, it never drops, renames or overwrites anything:
--
--      ALTER TABLE `cards`
--          ADD COLUMN `front_de` TEXT NULL DEFAULT NULL COMMENT 'The German question' AFTER `back`,
--          ADD COLUMN `back_de`  TEXT NULL DEFAULT NULL COMMENT 'The German answer'   AFTER `front_de`,
--          ADD COLUMN `front_en` TEXT NULL DEFAULT NULL COMMENT 'The English question' AFTER `back_de`,
--          ADD COLUMN `back_en`  TEXT NULL DEFAULT NULL COMMENT 'The English answer'   AFTER `front_en`;
--
--      UPDATE `cards`
--         SET `front_de` = `front`,
--             `back_de`  = `back`
--       WHERE `front_de` IS NULL;
--
--  The UPDATE only fills two new, empty columns from the text that is already
--  there. Running it twice changes nothing.
--
-- ===========================================================================
--  CHECKS (read-only, safe to run at any time)
-- ===========================================================================
--
--  DESCRIBE cards;
--
--  SELECT COUNT(*) AS cards_with_german FROM cards WHERE front_de IS NOT NULL AND TRIM(front_de) <> '';
--  -- expected: 161
--
--  SELECT COUNT(*) AS cards_with_english FROM cards WHERE front_en IS NOT NULL AND TRIM(front_en) <> '';
--  -- expected: 0 until somebody translates cards in the card dialog
--
--  SELECT COUNT(*) AS german_side_out_of_step FROM cards WHERE front <> front_de OR back <> back_de;
--  -- expected: 0, because the application writes both
--
--  SELECT COUNT(*) AS cards_without_any_language
--    FROM cards
--   WHERE (TRIM(front_de) = '' OR TRIM(back_de) = '')
--     AND (TRIM(front_en) = '' OR TRIM(back_en) = '');
--  -- expected: 0, a card without a complete language is refused by the API
